# Generated by Django 5.2.4 on 2025-07-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loo",
            name="cleanliness",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="loo",
            name="tags",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
