# Generated by Django 5.2.4 on 2025-07-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_loo_cleanliness_alter_loo_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loo",
            name="privacy",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
